name: hyaena-technologies-web

services:
  web-service:
    image: data-interchange-web:latest
    ports:
      - "8080/tcp"

  greptime-time-series:
    image: greptime/greptimedb:latest
    ports:
      - "8080/tcp"

  greptime-operator:
    image: greptime/greptimedb-operator:latest
    ports:
      - "8080/tcp"

  greptime-initializer:
    image: greptime/greptimedb-initializer:latest
    ports:
      - "8080/tcp"

  knative-cli: 
    image: gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
    ports:
      - "8080/tcp"

  knative-functions: 
    image: ghcr.io/knative/func/func:latest
    ports:
      - "8080/tcp"

  minio-storage:
    image: minio/minio:latest
    ports:
      - "8080/tcp"

  minio-operator:
    image: minio/operator:latest
    ports:
      - "8080/tcp"

  minio-control:
    image: minio/mc:latest
    ports:
      - "8080/tcp"

  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "8080/tcp"

  spice-authorization:
    image: authzed/spicedb:latest
    ports:
      - "8080/tcp"

  spice-operator:
    image: authzed/spicedb-operator:latest
    ports:
      - "8080/tcp"

  spice-zed:
    image: authzed/zed:latest
    ports:
      - "8080/tcp"

  surreal-graph:
    image: surrealdb/surrealdb:latest
    ports:
      - "8080/tcp"
