apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: greptime-operator
  name: greptime-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: greptime-operator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: greptime-operator
    spec:
      containers:
        - image: amd64/greptime/greptimedb-operator:latest
          name: greptime-operator
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
