apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: greptime-time-series
  name: greptime-time-series
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: greptime-time-series
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: greptime-time-series
    spec:
      containers:
        - image: amd64/greptime/greptimedb:latest
          name: greptime-time-series
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
