apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio-control
  name: minio-control
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-control
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: minio-control
    spec:
      containers:
        - image: minio/mc:latest
          name: minio-control
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
