apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio-storage
  name: minio-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-storage
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: minio-storage
    spec:
      containers:
        - image: minio/minio:latest
          name: minio-storage
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
