apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spice-authorization
  name: spice-authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spice-authorization
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: spice-authorization
    spec:
      containers:
        - image: authzed/spicedb:latest
          name: spice-authorization
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
