apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: surreal-graph
  name: surreal-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: surreal-graph
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: surreal-graph
    spec:
      containers:
        - image: amd64/surrealdb/surrealdb:latest
          name: surreal-graph
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
